app/app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("social_network.urls"))
]

app/social_network/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from . import views


app_name = "social_network"
urlpatterns = [
    path("", views.index, name="index"),
    path("", include("django.contrib.auth.urls")),
    path("sign-up/", views.sign_up, name="sign_up"),
]

app/social_network/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.utils.text import slugify


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(null=False, blank=False, upload_to='avatars', default='default/default_av.png')
    date_of_birth = models.DateField(blank=True, null=True)
    bio = models.TextField(null=True, blank=True)
    slug = models.SlugField(unique=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.username


class Following(models.Model):
    """Model describing user-follow-user relationship"""
    follower = models.ForeignKey(User, related_name='follower', on_delete=models.CASCADE)
    target_user = models.ForeignKey(User, related_name='target_user', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)


class Topic(models.Model):
    """Topic database model"""
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    image = models.ImageField(null=True, blank=True, upload_to='topic_images')
    slug = models.SlugField(unique=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Post(models.Model):
    """Post database model. Post doesn't have to be necessarily in topic"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/%Y/%m/', null=True, blank=True)
    text = models.TextField(blank=True, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(unique=True, null=False, blank=False)
    total_votes = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created_at",)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    vote_type = models.CharField(max_length=9, default="None")

    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    """Comment database model. User can comment posts"""
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/%Y/%m/', null=True, blank=True)
    text = models.TextField(blank=True)
    # parent_comment = models.ForeignKey(Comment, null=True, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)


class Subscription(models.Model):
    """Model, representing user-subscribe-to-topic relationship"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)


class UserBookmarking(models.Model):
    """Adding post to user's bookmarks. Creating user-post relationship"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


post_save.connect(create_user_profile, sender=User)

app/social_network/forms.py
from django import forms
from django.contrib.auth.models import User


class UserSignUpForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password1 = forms.CharField(label="Repeat password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

    def clean(self):
        if 'password' in self.cleaned_data and 'password1' in self.cleaned_data and \
                self.cleaned_data['password'] != self.cleaned_data['password1']:
            raise forms.ValidationError("The password does not match ")
        return self.cleaned_data

app/social_network/views.py
from django.shortcuts import render

from . import models, forms


def index(request):
    posts = models.Post.objects.all()

    context = {"posts": posts}
    return render(request, "social_network/index.html", context=context)


def sign_up(request):
    if request.method != "POST":
        user_form = forms.UserSignUpForm()

    else:
        user_form = forms.UserSignUpForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["password"])
            new_user.save()

            context = {"new_user": new_user}
            return render(request, "social_network/sign_up_done.html", context)

    context = {"user_form": user_form}
    return render(request, "social_network/sign_up.html", context)

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Fropy{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
</head>
<body>
    <header>
        <a class="logo" href="{% url "social_network:index" %}"><h1>Fropy</h1></a>
        {% if request.user.is_authenticated %}
        <nav>
            <ul class="nav__links">
                <li>
                    <a href="{% url "social_network:index" %}">Feed</a>
                </li>
                <li>
                    <a href="#">New Post</a>
                </li>
                <li>
                    <a href="#">{{ request.user.username }}</a>
                </li>
            </ul>
        </nav>
        {% else %}
            <nav>
                <ul class="nav__links">
                    <li>
                        <a href="{% url "social_network:index" %}">Feed</a>
                    </li>
                </ul>
            </nav>
            <div>
                <a class="cta" href="{% url "social_network:login" %}"><button class="button__sign-up">Log In</button></a>
                <a class="cta" href="{% url "social_network:sign_up" %}"><button class="button__sign-up">Sign Up</button></a>
            </div>
        {% endif %}
    </header>
    <br />

    <div class="content">
        {% block content %}

        {% endblock %}
    </div>

</body>
</html>

app/templates/social_network/index.html
{% extends 'base.html' %}

{% block title %}Fropy{% endblock %}

{% block content %}

    {% for post in posts %}
        <div>
            <div>
                <div>

                </div>
            </div>
        </div>
    {% empty %}
        <p>No posts yet</p>
    {% endfor %}

{% endblock %}

app/templates/social_network/sign_up.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}

    <h1>Sign up</h1>
    <form method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <button type="submit">Sign Up</button>
    </form>

{% endblock %}

app/templates/social_network/sign_up_done.html
{% extends "base.html" %}

{% block title %}Sign Up Done{% endblock %}

{% block content %}



{% endblock %}